"""empty message

Revision ID: 84af28900751
Revises: e9184f176b23
Create Date: 2022-11-01 19:34:41.270003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84af28900751'
down_revision = 'e9184f176b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass_reset',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass_reset')
    # ### end Alembic commands ###
