"""empty message

Revision ID: cb79afe173fe
Revises: f3ee659905ce
Create Date: 2022-10-29 19:44:34.236142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb79afe173fe'
down_revision = 'f3ee659905ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ticket_priority = sa.Enum('Normal', 'Urgent', name='ticketpriority')
    ticket_priority.create(op.get_bind())
    op.add_column('tickets', sa.Column('priority', sa.Enum('Normal', 'Urgent', name='ticketpriority'), nullable=False))
    op.add_column('tickets', sa.Column('deadline', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'deadline')
    op.drop_column('tickets', 'priority')
    # ### end Alembic commands ###
    pass
